import { showBetaFeature } from "@turtle/feature-flags";
import { createMetadata } from "@turtle/seo/metadata";
import {
  DATE_TIME_PATTERNS,
  formatDateTime,
} from "@turtle/utility/formatters/date-time";
import { formatString } from "@turtle/utility/formatters/string";
import { generateBarcode } from "@turtle/utility/generators/barcode";
import { generateQrCodeDataUrl } from "@turtle/utility/generators/qrcode";
import Image from "next/image";
import { HomeControls } from "./home-controls";

export const metadata = createMetadata({
  title: "Home",
  description: "Turtle web application.",
});

const demoDate = "2026-06-23T10:30:00Z";
const demoString = "turtle_utility_formatter_demo";
const demoCodeValue = "https://turtle.local/utility-demo";
const toSvgDataUri = (svg: string) =>
  `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;

export default async function Page() {
  const betaFeature = await showBetaFeature();
  const qrCodeDataUrl = await generateQrCodeDataUrl({
    value: demoCodeValue,
    width: 180,
    margin: 1,
  });
  const barcodeSvg = generateBarcode({
    text: "TURTLE-2026-0001",
    height: 12,
    scale: 2,
  });
  const formattedDate = formatDateTime(demoDate, {
    pattern: DATE_TIME_PATTERNS.dateOrdinalMonth,
  });
  const formattedString = formatString(demoString, {
    case: "upper",
    removeUnderscores: true,
  });

  return (
    <main className="min-h-svh p-6">
      <div className="mx-auto flex w-full max-w-4xl flex-col gap-6">
        {betaFeature ? (
          <div className="w-fit rounded-md bg-primary px-3 py-2 text-primary-foreground text-sm">
            Beta feature enabled
          </div>
        ) : null}

        <section className="flex flex-col gap-3">
          <div>
            <h1 className="font-medium text-2xl">Project ready</h1>
            <p className="text-muted-foreground text-sm">
              Internationalization is disabled in the web app for now. Utility
              helpers are rendered below for a quick visual check.
            </p>
          </div>
          <HomeControls />
        </section>

        <section className="grid gap-4 md:grid-cols-2">
          <div className="rounded-md border p-4">
            <h2 className="font-medium text-sm">Formatted date</h2>
            <p className="mt-2 text-lg">{formattedDate}</p>
            <p className="mt-1 font-mono text-muted-foreground text-xs">
              {demoDate}
            </p>
          </div>

          <div className="rounded-md border p-4">
            <h2 className="font-medium text-sm">Formatted string</h2>
            <p className="mt-2 text-lg">{formattedString}</p>
            <p className="mt-1 font-mono text-muted-foreground text-xs">
              {demoString}
            </p>
          </div>

          <div className="rounded-md border p-4">
            <h2 className="font-medium text-sm">QR code</h2>
            <Image
              alt="Demo QR code generated by @turtle/utility"
              className="mt-3 w-fit overflow-hidden rounded-md bg-white p-3"
              height={180}
              src={qrCodeDataUrl}
              unoptimized
              width={180}
            />
            <p className="mt-2 font-mono text-muted-foreground text-xs">
              {demoCodeValue}
            </p>
          </div>

          <div className="rounded-md border p-4">
            <h2 className="font-medium text-sm">Barcode</h2>
            <Image
              alt="Demo barcode generated by @turtle/utility"
              className="mt-3 w-fit overflow-hidden rounded-md bg-white p-3"
              height={80}
              src={toSvgDataUri(barcodeSvg)}
              unoptimized
              width={260}
            />
            <p className="mt-2 font-mono text-muted-foreground text-xs">
              TURTLE-2026-0001
            </p>
          </div>
        </section>

        <div className="font-mono text-muted-foreground text-xs">
          Press <kbd>d</kbd> to toggle dark mode.
        </div>
      </div>
    </main>
  );
}
